version: '3.7'

services:
  server:
    build:
      context: ./src/node
      dockerfile: Dockerfile
    image: ws-server
    container_name: ws
    command: 'yarn start'
    volumes:
      - ./src/:/code
    ports:
      - "5000:5000"
    # env_file: ./src/.env
    environment:
      - NODE_ENV=development
