version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: wsocket_img
    command: 'python server.py'
    volumes:
      - ./:/src
    ports:
      - "80:8000"
   
